apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: freact
  name: freact
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freact
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: freact
    spec:
      containers:
      - image: azkadevops/freact:2.1
        name: freact
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: APP_TYPE
          valueFrom:
            configMapKeyRef:
              name: reactconfig
              key: app
        - name: PROFILES
          valueFrom:
            configMapKeyRef:
              name: reactconfig
              key: profile

        resources: {}
status: {}
