name: Push image on dockerhub

on:
  push:
    branches:
      - main
      - release/v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t azkadevops/freact:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTERY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTERY_PASSWORD }}
          
      - name: push Docker Image
        run: |
          docker push azkadevops/freact:latest
